server:
  port: 8083
spring:
  application:
    name: database-server
  datasource:
    password: 1qazXSW@
    url: jdbc:postgresql://localhost:5432/family
    username: testuser
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true