services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 1qazXSW@
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    image: jarek1725/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

    networks:
      - spring

  family:
    image: jarek1725/family:latest
    container_name: family
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
      - database-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  family-member:
    image: jarek1725/family-member:latest
    container_name: family-member
    ports:
      - "8082:8082"
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
      - database-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  database-server:
    image: jarek1725/database-server:latest
    container_name: database-server
    ports:
      - "8083:8083"
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: